### ISSUE TITLE
detection error

### ISSUE THREAD

**Issue by SaddamBInSyed** [neuralet/neuralet#100]
**Describe the bug**
person distance prediction is always showing red color (wrong) when only one person standing in the camera.

**Screenshots**
![image](https://user-images.githubusercontent.com/10062672/82142118-20e3f180-984b-11ea-9586-fe7d393ad8f3.png)
 
running the code on jetson nano (4.3) and viewing the client on the desktop (chrome).
please advise.

**Comment by mrn-mln** [comment]
@SaddamBInSyed It seems something is wrong with visualization when there is one object (1 person) at the image. I try to reproduce the bug and fix it.

**Comment by mrn-mln** [comment]
#101 The bug is fixed.
