### ISSUE TITLE
Adding Pedestrian Detection Models for x86

### ISSUE THREAD

**Issue by alpha-carinae29** [neuralet/neuralet#116]
Hi everyone,
I found out that only one model is available for x86 devices and this model is a COCO pre-trained model.
So I decided to train different pedestrian detection model with TensorFlow object detection API. I have trained three different object detector with Oxford Town Center dataset so far and I wanted to upload these models somewhere so I can download them in smart distancing app, however usually these models have large size and GitHub repositories may be not the best platform for uploading them.
@mhejrati what is your suggestions?

**Comment by mhejrati** [comment]
We use this repo for that purpose:
https://github.com/neuralet/neuralet-models

Make a PR there and I can merge.

**Comment by alpha-carinae29** [comment]
Yeah but some of the model's checkpoints are above 100MB and GitHub have restrictions on large files.

**Comment by mrn-mln** [comment]
@alpha-carinae29 instead of checkpoints just add a frozen graph (.pb file) to the repo.

**Comment by alpha-carinae29** [comment]
Thanks @mrn-mln, however `.pb` files for faster RCNN models are above 100MB

**Comment by alpha-carinae29** [comment]
@mhejrati I pushed two models in here:
https://github.com/neuralet/neuralet-models/pull/6
