### ISSUE TITLE
Video for testing pedestrian detection generalization

### ISSUE THREAD

**Issue by mrn-mln** [neuralet/neuralet#122]
Hi,
I've found a video which is helpful to test the generalization of trained models on the social-distancing app.
Please keep related topics and share sample videos here.

https://github.com/opencv/opencv/blob/master/samples/data/vtest.avi

**Comment by piorun369** [comment]
Thanks. Does anyone have a link to the original video for the demo: TownCentreXVID.avi?

The link is broken:
neuralet/applications/smart-distancing/download_sample_video.sh

wget http://www.robots.ox.ac.uk/ActiveVision/Research/Projects/2009bbenfold_headpose/Datasets/TownCentreXVID.avi -O data/TownCentreXVID.avi

**Comment by JsonSadler** [comment]
@mrn-mln  I think you can close this now

@cachro2 Check [https://github.com/neuralet/smart-social-distancing/pull/26](https://github.com/neuralet/smart-social-distancing/pull/26), videos are changed as the original video has been removed due to some privacy issues.

**Comment by JsonSadler** [comment]
I think this can be closed now as https://github.com/neuralet/smart-social-distancing/pull/26 is merged and closed @mrn-mln @mhejrati
