### ISSUE TITLE
collaborate thru python only

### ISSUE THREAD

**Issue by orapradeep** [neuralet/neuralet#126]
I am not sure about dockers, can i colloborate through python code developement??

**Comment by mrn-mln** [comment]
@orapradeep Docker is a convenient service for installing all packages and delivering software, however, if you are not sure about using it, you can install all packages/libraries manually and run the application by python.

**Comment by orapradeep** [comment]
Thx @mrn-mln any pointers on the structure will be helpful

**Comment by mrn-mln** [comment]
@orapradeep 
After Cloning the repo go to ` neuralet/applications/smart-distancing/`
For x86 devices open `config-x86.ini` file and set your config.
Run the app by this script `python neuralet-distancing.py --config config-x86.ini`
Note: For running the app you should install needed packages/frameworks/libraries such as flask,/ tensorflow, numpy ...
Please let me know if you have any issue.

**Comment by JsonSadler** [comment]
@orapradeep Thanks for your willingness, feel free to collaborate and make PR's, just mention that you need help with the dockers.
