### ISSUE TITLE
Module not found in docker image for object detection training

### ISSUE THREAD

**Issue by FSet89** [neuralet/neuralet#141]
**Describe the bug**

**To Reproduce**
1. Build and launch docker container from source according to [this](https://neuralet.com/article/quantization-of-tensorflow-object-detection-api-models/) guide
2. run python object_detection_model_main.py --help

**Expected behavior**
The python script should run and display help page

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04

**Additional context**
When trying to run the script, I got errors for missing modules:

```
root@89b340f3a5bf:/models/research# python object_detection/model_main.py 
Traceback (most recent call last):
  File "object_detection/model_main.py", line 25, in <module>
    from object_detection import model_lib
  File "/models/research/object_detection/model_lib.py", line 27, in <module>
    import tf_slim as slim
ModuleNotFoundError: No module named 'tf_slim'
```
Same with lvis.

**Comment by alpha-carinae29** [comment]
Hi @FSet89, 
Can you please test one more time with this modification?

**Comment by FSet89** [comment]
Hi, actually I fixed by pulling the container form docker hub (2nd option), thank you anyway

**Comment by FarzanehRoshanzamir** [comment]
Same problem!
What is the difference between building from this docker file and pulling from docker hub?!

Update:
Problem solved by adding these lines into docker file:
`RUN pip install tf-slim scipy lvis`

**Comment by mhejrati** [comment]
PR #141 addresses this
