### ISSUE TITLE
UI Improvement: Show statistical and historical data on the web GUI

### ISSUE THREAD

**Issue by mhejrati** [neuralet/neuralet#19]

**Comment by alpha-carinae29** [comment]
Hi @mhejrati.
I am working on this feature, I gonna create a CSV logger to store all of the objects and distances data in CSV files, then perform some statistical and historical analysis.

**Comment by mrn-mln** [comment]
Hi @mhejrati.
I have worked on this issue. Some javascript modules are added to your web interface in order to visualize csv files. I will send a PR to you.
