### ISSUE TITLE
Modify configuration and parameters from web GUI

### ISSUE THREAD

**Issue by mhejrati** [neuralet/neuralet#25]
* Configuring input sources for cameras

**Comment by evantkchong** [comment]
@mhejrati Hello, I'd like to contribute to this issue if you'll have me! 

I suppose this task involves exposing the `VideoPath` parameter from a given config.ini and saving changes made through the web GUI?

**Comment by mats-claassen** [comment]
Hi @MoltenMuffins have you made any progress on this?
If you haven't I'd like to take it on.

And regarding your question, I believe it involves what you mention but in future could be expanded to support more configurations. For example, to modify some parameter of the model. Am I right @mhejrati ?
