### ISSUE TITLE
Show high-risk areas as a heatmap

### ISSUE THREAD

**Issue by mhejrati** [neuralet/neuralet#26]

**Comment by mats-claassen** [comment]
Hi @mhejrati, we could start working on this. I have a few questions/comments about this feature:
1- First we need to save the detection location to the csv file (or other analytics storage). Have you thought about the format for this? Should we save the box coordinates or only the center for each box? (Or maybe the center of the bottom side of the box) For example it could be a stringified array of [x1, y1, x2, y2, (next box) x1, y1, x2, y2, ...] (or only x and y if we only save the center). For violations we only need to save the indexes of the violating boxes.
2- Then, the heatmap on the web side should it take into account the whole history of entries or have a parameter for how far to go backwards? Should we show two heatmaps, one for detections in general and another for violations, or just one?
3- The heatmap renders without a background from the camera, right? Or optionally if camera feed is available we could take one image from the camera feed and add it as background to the heatmap for reference.
4- If the heatmap should include detections and not only violations then we need to handle the depth perspective. Any ideas for this? Or it could be left for a second version
