### ISSUE TITLE
Improve web GUI web streaming performance

### ISSUE THREAD

**Issue by mhejrati** [neuralet/neuralet#27]

**Comment by JsonSadler** [comment]
ongoing in #67

**Comment by mohammad7t** [comment]
@JsonSadler I couldn't add you to reviewers of https://github.com/neuralet/smart-social-distancing/pull/3. Please do review and let me know if there is any part that highly requires more documentation.

**Comment by mohammad7t** [comment]
The above pull request improves the performance too.
