### ISSUE TITLE
Improve detection box filtering strategies

### ISSUE THREAD

**Issue by mhejrati** [neuralet/neuralet#30]
We can improve detections using:
- Scene priors
- Background/Foreground subtraction and modeling

@alpha-carinae29 & @mrn-mln I suggest you take a look at this.

**Comment by alpha-carinae29** [comment]
@mhejrati please move this issue to fine-tuning and calibration milestone

**Comment by alpha-carinae29** [comment]
I worked on this issue in last days.
I have implemented a background subtraction with `cv.createBackgroundSubtractorMOG2` module.
here is a result on Oxford Town Center:
![photo_2020-05-17_02-07-53](https://user-images.githubusercontent.com/63186529/82130752-72589600-97e3-11ea-9c9d-8a6f27313983.jpg)
![photo_2020-05-17_02-07-57](https://user-images.githubusercontent.com/63186529/82130756-7ab0d100-97e3-11ea-85e3-898181b61c68.jpg)
Now I am trying to filter object detection's output based on this information. To doing this I will filter boxes that the percentage of background pixels more than a threshold.

**Comment by alpha-carinae29** [comment]
Also I am implementing a prior distribution of bounding boxes for each pixel in the image. (only mean and variance not the whole distribution.) 
To this end I computed the average and variance of width and height of bounding boxes for the centroids of the boxes recurrently with [Welford algorithm](https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Welford's_online_algorithm). After the training Phase, for each detected bounding box we compare its width and height with the prior mean and variance and if we detect an outlier we eliminate the bounding box.

**Comment by alpha-carinae29** [comment]
@mhejrati please mark it as "in progress".
