### ISSUE TITLE
x86-64 node release

### ISSUE THREAD

**Issue by mhejrati** [neuralet/neuralet#31]
Adding models that run on CPU and GPU on x86-64 nodes. 

Definition of done:
1- A new detectors in libs/detectors that calls a GPU or CPU model
2- A new dockerfile to build the application container for CPU
3- A new dockerfile to build the application container for NVIDIA GPU, using NVIDIA Docker
4- Documentation for running and building the application.

**Comment by HHIR** [comment]
@mhejrati If there is any help needed here, please explain briefly how can I proceed?

**Comment by mhejrati** [comment]
@HHIR Thanks for reaching out. I just added more details to the issue. Please review and let me know if this makes sense. We may start working on this soon.
