### ISSUE TITLE
Annotating of The Remaining Frames of The Oxford Town Center Dataset

### ISSUE THREAD

**Issue by alpha-carinae29** [neuralet/neuralet#49]
As the annotations only exist for the first 2500 frames of the [Oxford Town Center Dataset](https://www.robots.ox.ac.uk/ActiveVision/Research/Projects/2009bbenfold_headpose/project.html) it helps training accurate models for pedestrian detection if someone can annotate the ramaining frames and add it to the bottom of the annotation [CSV file](https://www.robots.ox.ac.uk/ActiveVision/Research/Projects/2009bbenfold_headpose/Datasets/TownCentre-groundtruth.top).

**Comment by lchunleo** [comment]
As the town Center dataset is not longer available, do anyone know the annotation format (csv)? thank you
