### ISSUE TITLE
Could you create a bird's eye view for surveillance video?

### ISSUE THREAD

**Issue by hieubz** [neuralet/neuralet#55]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hieubz** [comment]
I think it will be useful for your lib and I saw some location accuracy problems when I tried to map camera view to bird's eye view.

**Comment by mhejrati** [comment]
@PhamDuyHieutb Can you please elaborate? There is currently a bird's eye map of detected persons but I imagine you are looking for something else.

**Comment by hieubz** [comment]
I mean that in your smart social distancing app, you can add a bird's eye map as a feature in your open source. (for example in this video  https://www.youtube.com/watch?v=15iIV1Lff-M)
I think it will be useful for your project.

**Comment by mhejrati** [comment]
It is already implemented, have you tried our latest version?
