### ISSUE TITLE
Video file for face-mask detection

### ISSUE THREAD

**Issue by mrn-mln** [neuralet/neuralet#95]
For testing face-mask detection, I need a video benchmark for creating a demo and test the capability of the model in a real-world scenario. Currently, we don't have video files in which people wear a face mask.

![image](https://user-images.githubusercontent.com/63195774/82118271-52958380-978b-11ea-841b-ce55a5e0ce81.png)

**Comment by mrn-mln** [comment]
@rkgits, @mhejrati I've searched for the videos but it seems there are no proper videos for our task. However, there are lots of videos from news related to the face mask issue.
Sample videos:
https://www.youtube.com/watch?v=hekZBf8oUq0
https://www.youtube.com/watch?v=scStYflhltg
https://www.youtube.com/watch?v=HNMnu0Z7TgY
We can cut some parts of the videos and release a benchmark which is useful for the covid19 developer community.

**Comment by mhejrati** [comment]
Some more videos with creative common license:
https://www.youtube.com/watch?v=MEj0ayTeEnU
https://www.youtube.com/watch?v=V54hhnyAntU
https://www.youtube.com/watch?v=5_0LobssR9A
https://www.youtube.com/watch?v=A77GS1Z5uvg
https://www.youtube.com/watch?v=EeuneefPTyY
https://www.youtube.com/watch?v=KM5oNfLlhnc
https://www.youtube.com/watch?v=WvK6QP8GqzY
https://www.youtube.com/watch?v=EIY9xJc4s0Q
https://www.youtube.com/watch?v=_FPFLmqYRC0
https://www.youtube.com/watch?v=ZAKOzzMZ2Bc
https://www.youtube.com/watch?v=UGX50EpWtPQ
https://www.youtube.com/watch?v=nf4bZgHsa5E
https://www.youtube.com/watch?v=HNMnu0Z7TgY

**Comment by mrn-mln** [comment]
Good video for starting.
https://www.youtube.com/watch?v=7-IEW0cr5To
@mhejrati I select these videos which you'd had shared to start working on [issue 106](https://github.com/neuralet/neuralet/issues/106)
https://www.youtube.com/watch?v=V54hhnyAntU
https://www.youtube.com/watch?v=5_0LobssR9A
https://www.youtube.com/watch?v=EeuneefPTyY
https://www.youtube.com/watch?v=_FPFLmqYRC0
